baseurl = "https://www.ees4760.jgilligan.org"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "EES 4760/5760"
theme = "hugo-syllabus"
#disqusShortname = ""
enableRobotsTXT = true
# googleAnalytics = "UA-101117636-4"
paginate = 10
relativeurls = true
publishDir = "public"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "_scripts$", "_data$", "\\.gitkeep"]

[blackfriday]
  smartypants = true
  latexDashes = true
  smartDashes = true
  hrefTargetBlank = true
  angledQuotes = false
  fractions = false

[permalinks]
  post = "/:year/:month/:slug/"
  reading = "/reading/:slug"
  assignment = "/assignment/:slug"
  lab = "/lab/:slug"
  lab_docs = "/lab_docs/:slug"
  lab_solutions = "/lab_solutions/:slug"
  homework_solutions = "/homework_solutions/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Jonathan Gilligan"
  bio = ""
  job = "Associate Professor"
  location = "Vanderbilt University"
  gravatarEmail = "jonathan.gilligan@gmail.com"
  # Your profile picture
#  picture = ""
  homepage = "https://www.jonathangilligan.org"
  twitter = "jg_environ"

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "overview"
  name = "Overview"
  pre = "<i class=\"fa fa-globe\"></i>"
  url = "/overview"
[[menu.main]]
  weight = 3
  identifier = "schedule"
  name = "Schedule"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/schedule"
[[menu.main]]
  weight = 4
  identifier = "projects"
  name = "Projects"
  pre = "<i class=\"material-icons\">near_me</i>"
  url = "/projects"
[[menu.main]]
  weight = 5
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"
[[menu.main]]
  weight = 6
  identifier = "downloads"
  name = "Downloads"
  pre = "<i class=\"material-icons\">get_app</i>"
  url = "/downloads"
[[menu.main]]
  weight = 7
  identifier = "tools"
  name = "Tools"
  pre = "<i class=\"material-icons\">build</i>"
  url = "/tools"

[[menu.footer]]
  weight = 2
  identifier = "GitHub"
  name = "Class Repos"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/gilligan-ees-4760"

[params]
  profname = "Jonathan Gilligan"
  dateFormat = "January 2, 2006"
  background = "img/course_banner_cropped.jpg"
  math = "true"
  backgroundColor = "white"
  backgroundSize = "cover"
  backgroundBlendMode = "multiply"
  backgroundRepeat = "repeat-y"
  shortCourseName = "EES 4760/5760"
  fullCourseName = "EES 4760/5760: Agent- and Individual-Based Computational Modeling"
  semester = "Fall 2019"
  courseCatalogEntry = " Applications in natural, social, and behavioral sciences and engineering. Designing, programming, and documenting models. Using models for experiments. Examples from environmental science, ecology, economics, urban planning, and medicine. Familiarity with basic statistics and proficiency in algebra are expected. [3] (MNS)"
  fontAwesomePro = "sha384-POYwD7xcktv3gUeZO5s/9nUbRJG/WOmV6jfEGikMJu77LGYO8Rfs2X7URG822aum"
  siteGitHub = "https://github.com/gilligan-ees-4760-2019/EES_4760_5760_website.git"

  [params.lectures]
    times = "TR 11:00--12:15"
    classroom = "SC 2200"

  [params.prof]
    name = "Jonathan Gilligan"
    lastname = "Gilligan"
    title = "Prof."
    email = "jonathan.gilligan@vanderbilt.edu"
    phone = "322-2420"
    url = "www.jonathangilligan.org"
    office = "Stevenson 5725 (7th floor of building #5)"
    officeHours = "Tues. 2:00--3:00, Wed. 10:30--11:30, or by appointment"

  [params.ta]
    hasTA = false
    name = "TBA"
    lastname = "TBA"
    title = "Ms."
    email = "TBA@vanderbilt.edu"
    office = "TBA"
    officeHours = "TBA"

  [params.assignments]
    labs = false
    homework = true
    reading = true

  [params.ip]
    copyright = "Copyright 2018, <a href=\"https://www.jonathangilligan.org\" target=\"_blank\">Jonathan Gilligan</a>."
    licenseIcon = "/img/cc-by.svg"
    licenseURL = "https://creativecommons.org/licenses/by/4.0/"
